//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTable
    {
        public string BankID { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string BankName_Eng { get; set; }
        public string AbBankName { get; set; }
        public Nullable<bool> isNonBank { get; set; }
        public Nullable<bool> hasCreditCard { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public string VendorCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<decimal> LoanRate { get; set; }
        public string ContactEmail { get; set; }
        public string ContactName { get; set; }
        public string ContactTel { get; set; }
        public string EmailBody { get; set; }
        public string EmailHeader { get; set; }
    }
}
