//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTable
    {
        public long ReportID { get; set; }
        public string ReportCode { get; set; }
        public string ReportNameTH { get; set; }
        public string ReportNameEN { get; set; }
        public Nullable<int> ReportType { get; set; }
        public string ReportFileName { get; set; }
        public string ReportPath { get; set; }
        public string ReportDBConnection { get; set; }
        public string ReportProcedure { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
