//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCriteriaTable
    {
        public long CriteriaID { get; set; }
        public string ReportCode { get; set; }
        public string CriteriaType { get; set; }
        public string CriteriaName { get; set; }
        public string CriteriaLabel { get; set; }
        public Nullable<int> CriteriaRow { get; set; }
        public string CriteriaIndex { get; set; }
        public string EventOn { get; set; }
        public string CriteriaQuery { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
