//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_EMPLOYEEVw
    {
        public string RowID { get; set; }
        public string CP_CODE { get; set; }
        public string EM_CODE { get; set; }
        public string EM_PRENAME_T { get; set; }
        public string EM_PRENAME_E { get; set; }
        public string EM_NAME_T { get; set; }
        public string EM_NAME_E { get; set; }
        public string EM_SURNAME_T { get; set; }
        public string EM_SURNAME_E { get; set; }
        public string EM_NICKNAME { get; set; }
        public Nullable<System.DateTime> EM_BIRTHDATE { get; set; }
        public string EM_SEX { get; set; }
        public string EM_MOBILE { get; set; }
        public string EM_MAIL { get; set; }
        public string EM_POSITION_T { get; set; }
        public string EM_POSITION_E { get; set; }
        public string EM_PositionCode { get; set; }
        public string EM_SUBPOSITION_T { get; set; }
        public string EM_SUBPOSITION_E { get; set; }
        public string EM_JobroleCode { get; set; }
        public string EM_UNIT_T { get; set; }
        public string EM_UNIT_E { get; set; }
        public string EM_COMPANY_T { get; set; }
        public string EM_COMPANY_E { get; set; }
        public string EM_PICTURE_PATH { get; set; }
        public Nullable<System.DateTime> EM_STARTJOBD { get; set; }
        public Nullable<System.DateTime> EM_SERVICEDATE { get; set; }
        public string EL_TNAME { get; set; }
        public string EM_Iden { get; set; }
        public string EM_UNIT_T_Code { get; set; }
        public string EM_GROUP_CODE { get; set; }
        public string EM_GROUP_NAME_T { get; set; }
        public string EM_GROUP_NAME_E { get; set; }
        public Nullable<System.DateTime> EM_ENDJOBDATE { get; set; }
        public Nullable<bool> EM_INACTIVE { get; set; }
        public string EM_SL_UNIT_CODE_U1 { get; set; }
        public string EM_SL_TNAME_U1 { get; set; }
        public string EM_SL_ENAME_U1 { get; set; }
        public string EM_SL_UNIT_CODE_U2 { get; set; }
        public string EM_SL_TNAME_U2 { get; set; }
        public string EM_SL_ENAME_U2 { get; set; }
        public string EM_SL_UNIT_CODE_U3 { get; set; }
        public string EM_SL_TNAME_U3 { get; set; }
        public string EM_SL_ENAME_U3 { get; set; }
        public string EM_SL_UNIT_CODE_U4 { get; set; }
        public string EM_SL_TNAME_U4 { get; set; }
        public string EM_SL_ENAME_U4 { get; set; }
        public string EM_SL_UNIT_CODE_U5 { get; set; }
        public string EM_SL_TNAME_U5 { get; set; }
        public string EM_SL_ENAME_U5 { get; set; }
        public string EM_SL_UNIT_CODE_U6 { get; set; }
        public string EM_SL_TNAME_U6 { get; set; }
        public string EM_SL_ENAME_U6 { get; set; }
        public string EM_USERNAME { get; set; }
        public string EM_EmployeeTypeCode { get; set; }
        public string EM_EmployeeTypeName { get; set; }
        public string EM_CombinationCode { get; set; }
        public string EM_CombinationName { get; set; }
        public string EM_AddressTypeCode_01 { get; set; }
        public string EM_AddressTypeName_01 { get; set; }
        public string EM_Address1_01 { get; set; }
        public string EM_Address2_01 { get; set; }
        public string EM_CityArea_01 { get; set; }
        public string EM_City_01 { get; set; }
        public string EM_State_01 { get; set; }
        public string EM_Country_01 { get; set; }
        public string EM_PostelCode_01 { get; set; }
        public string EM_AddressTypeCode_02 { get; set; }
        public string EM_AddressTypeName_02 { get; set; }
        public string EM_Address1_02 { get; set; }
        public string EM_Address2_02 { get; set; }
        public string EM_CityArea_02 { get; set; }
        public string EM_City_02 { get; set; }
        public string EM_State_02 { get; set; }
        public string EM_Country_02 { get; set; }
        public string EM_PostelCode_02 { get; set; }
    }
}
