//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallVisit
    {
        public int CallVisitID { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string LineID { get; set; }
        public string Address { get; set; }
        public string Building { get; set; }
        public string Moo { get; set; }
        public string Floor { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public Nullable<int> SubDistrictID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string ZipCode { get; set; }
        public string CountryCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyPosition { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyBuilding { get; set; }
        public string CompanyMoo { get; set; }
        public string CompanyFloor { get; set; }
        public string CompanySoi { get; set; }
        public string CompanyRoad { get; set; }
        public Nullable<int> CompanySubDistrictID { get; set; }
        public Nullable<int> CompanyDistrictID { get; set; }
        public Nullable<int> CompanyProvinceID { get; set; }
        public string CompanyZipCode { get; set; }
        public string CompanyCountryCode { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public Nullable<int> AgeID { get; set; }
        public Nullable<int> OccupationID { get; set; }
        public string OtherOccupation { get; set; }
        public Nullable<int> SalaryID { get; set; }
        public Nullable<int> BudgetID { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> SaleCode { get; set; }
        public string IDCard { get; set; }
        public Nullable<bool> IsForeign { get; set; }
    }
}
