//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckRoomBrokenTran
    {
        public int BrokenID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> RentID { get; set; }
        public string Description { get; set; }
        public Nullable<long> Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<long> Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
    }
}
