//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactReasonCancel
    {
        public int ContactReasonCancelID { get; set; }
        public Nullable<long> ReservationsID { get; set; }
        public Nullable<int> RentID { get; set; }
        public int ReasonCancelFormID { get; set; }
        public string Other { get; set; }
        public Nullable<long> Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
    }
}
