//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Master_NamePrefix
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public string FullText { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsDelete { get; set; }
    }
}
