//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Lead
    {
        public string ItemID { get; set; }
        public int TransID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FirstNameEng { get; set; }
        public string LastNameEng { get; set; }
        public string Project { get; set; }
        public string Tel1 { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Type { get; set; }
        public string Gender { get; set; }
        public string Datasource { get; set; }
        public string JobTitle { get; set; }
        public string JobLocation { get; set; }
        public string AddressNo { get; set; }
        public string Moo { get; set; }
        public string Soi { get; set; }
        public string Village { get; set; }
        public string Road { get; set; }
        public string SubDistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Status { get; set; }
        public string SysStatus { get; set; }
        public string SysStatusDesc { get; set; }
        public bool SMS_Flag { get; set; }
        public bool DM_Flag { get; set; }
        public bool IsDelete { get; set; }
        public string LineID { get; set; }
        public string Remark { get; set; }
        public string HouseNumber { get; set; }
        public string Budget { get; set; }
        public string RoomType { get; set; }
        public Nullable<bool> IsJuristic { get; set; }
        public string JuristicBranchID { get; set; }
        public string JuristicBranchName { get; set; }
        public string MemberPassword { get; set; }
        public Nullable<long> VisitID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<long> UnitsID { get; set; }
    }
}
