//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Contacts
    {
        public long ContactsID { get; set; }
        public string MemberID { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public string FromLeadID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CitizenID { get; set; }
        public Nullable<System.DateTime> CitizenIssue { get; set; }
        public Nullable<System.DateTime> CitizenExp { get; set; }
        public string CitizenProvince { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Position { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string FacebookURL { get; set; }
        public string LineID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string ProfileImg { get; set; }
        public string ProfileImg_Byte { get; set; }
        public string AddressNo { get; set; }
        public string Moo { get; set; }
        public string Soi { get; set; }
        public string Village { get; set; }
        public string Road { get; set; }
        public string SubDistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string AddressNo_Reg { get; set; }
        public string Moo_Reg { get; set; }
        public string Soi_Reg { get; set; }
        public string Village_Reg { get; set; }
        public string Road_Reg { get; set; }
        public string SubDistrict_Reg { get; set; }
        public string District_Reg { get; set; }
        public string Province_Reg { get; set; }
        public string ZipCode_Reg { get; set; }
        public string Country_Reg { get; set; }
        public string AddressNo_Work { get; set; }
        public string Moo_Work { get; set; }
        public string Soi_Work { get; set; }
        public string Village_Work { get; set; }
        public string Road_Work { get; set; }
        public string SubDistrict_Work { get; set; }
        public string District_Work { get; set; }
        public string Province_Work { get; set; }
        public string ZipCode_Work { get; set; }
        public string Country_Work { get; set; }
        public string Map_Address { get; set; }
        public string Map_AddressReg { get; set; }
        public string Map_AddressWork { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string DataSource { get; set; }
        public string ExcelFileName { get; set; }
        public string BillingName { get; set; }
        public string BillingPlace { get; set; }
        public string BillingTime { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> CreditLimitApprove { get; set; }
        public string CreditTerm { get; set; }
        public string CreditTermApprove { get; set; }
        public string CreditTermApproveBy { get; set; }
        public Nullable<System.DateTime> CreditTermApproveDate { get; set; }
        public string Owner { get; set; }
        public Nullable<bool> SMS_Flag { get; set; }
        public Nullable<bool> DM_Flag { get; set; }
        public Nullable<bool> PreferToDM { get; set; }
        public Nullable<bool> IsShareOnMobile { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> ContactPerMonth { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> Grade { get; set; }
        public string Location { get; set; }
        public string LocationImg_Byte { get; set; }
        public string Product { get; set; }
        public string Status { get; set; }
        public string OfficeName { get; set; }
        public Nullable<bool> IsFromMobile { get; set; }
        public string Nationality { get; set; }
        public string Race { get; set; }
        public string AddressNo_Doc { get; set; }
        public string Moo_Doc { get; set; }
        public string Soi_Doc { get; set; }
        public string Village_Doc { get; set; }
        public string Road_Doc { get; set; }
        public string SubDistrict_Doc { get; set; }
        public string District_Doc { get; set; }
        public string Province_Doc { get; set; }
        public string ZipCode_Doc { get; set; }
        public string Country_Doc { get; set; }
        public string PassportID { get; set; }
        public string Origin { get; set; }
        public string RefMemberID { get; set; }
        public string FirstNameEng { get; set; }
        public string LastNameEng { get; set; }
        public Nullable<bool> IsJuristic { get; set; }
        public Nullable<bool> IsThailand { get; set; }
        public Nullable<bool> IsVIP { get; set; }
        public string ExigentFirstName { get; set; }
        public string ExigentLastName { get; set; }
        public string ExigentTel { get; set; }
        public string ExigentRelation { get; set; }
        public string JuristicBranchID { get; set; }
        public string JuristicBranchName { get; set; }
        public Nullable<int> GradeBuy { get; set; }
        public Nullable<System.DateTime> CitizenIs { get; set; }
        public string MemberPassword { get; set; }
        public string ExigentEmail { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> UnExpireIDCard { get; set; }
        public Nullable<bool> IsForeign { get; set; }
        public string JuristicPerson { get; set; }
    }
}
