//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositTable
    {
        public long DepositID { get; set; }
        public string DepositNo { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public Nullable<long> DSContactID { get; set; }
        public Nullable<long> DSTypeID { get; set; }
        public Nullable<long> DeveloperID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<bool> IsRent { get; set; }
        public Nullable<decimal> RentPriceStart { get; set; }
        public Nullable<decimal> RentPriceEnd { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<decimal> SalePriceStart { get; set; }
        public Nullable<decimal> SalePriceEnd { get; set; }
        public string CheckRoomRemarkDeposit { get; set; }
        public string FacilityOther { get; set; }
        public string FacilityRemark { get; set; }
        public Nullable<long> InChargeBy { get; set; }
        public Nullable<System.DateTime> DepositStart { get; set; }
        public Nullable<System.DateTime> DepositEnd { get; set; }
        public Nullable<decimal> MaintenanceCharge { get; set; }
        public Nullable<decimal> WaterCharge { get; set; }
        public Nullable<long> CountKey { get; set; }
        public Nullable<bool> KeyIsAgent { get; set; }
        public Nullable<bool> KeyIsJuristic { get; set; }
        public string ProjectAddress { get; set; }
        public string DocRef { get; set; }
        public Nullable<long> Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<long> Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string ReasonCancel { get; set; }
        public Nullable<decimal> RateComCopyContact { get; set; }
    }
}
