//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositAttachment
    {
        public int DepositAttachmentID { get; set; }
        public Nullable<long> DepositID { get; set; }
        public string FilePath { get; set; }
        public string RevisedBy { get; set; }
        public Nullable<System.DateTime> RevisedDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
