//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PMdbEntities1 : DbContext
    {
        public PMdbEntities1()
            : base("name=PMdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckRoomBrokenPayment> CheckRoomBrokenPayments { get; set; }
        public virtual DbSet<CheckRoomBrokenTran> CheckRoomBrokenTrans { get; set; }
        public virtual DbSet<CheckRoomMasterTable> CheckRoomMasterTables { get; set; }
        public virtual DbSet<CheckRoomTran> CheckRoomTrans { get; set; }
        public virtual DbSet<CheckTypeMasterTable> CheckTypeMasterTables { get; set; }
        public virtual DbSet<ContactBankTable> ContactBankTables { get; set; }
        public virtual DbSet<CRM_Lead> CRM_Lead { get; set; }
        public virtual DbSet<CRM_Master_NamePrefix> CRM_Master_NamePrefix { get; set; }
        public virtual DbSet<CustomerTypeTable> CustomerTypeTables { get; set; }
        public virtual DbSet<DataSourceTable> DataSourceTables { get; set; }
        public virtual DbSet<DepositTable> DepositTables { get; set; }
        public virtual DbSet<DevelopmentTable> DevelopmentTables { get; set; }
        public virtual DbSet<DocumentCodeTable> DocumentCodeTables { get; set; }
        public virtual DbSet<FacilityMasterTable> FacilityMasterTables { get; set; }
        public virtual DbSet<FacilityTran> FacilityTrans { get; set; }
        public virtual DbSet<ImageRoomTable> ImageRoomTables { get; set; }
        public virtual DbSet<ImageTable> ImageTables { get; set; }
        public virtual DbSet<ProjectDetailTable> ProjectDetailTables { get; set; }
        public virtual DbSet<RentTypeMasterTable> RentTypeMasterTables { get; set; }
        public virtual DbSet<ResaleTable> ResaleTables { get; set; }
        public virtual DbSet<UnitsDetialTable> UnitsDetialTables { get; set; }
        public virtual DbSet<UnitsTable> UnitsTables { get; set; }
        public virtual DbSet<DMPS_UnitTypeTable> DMPS_UnitTypeTable { get; set; }
        public virtual DbSet<VisitTypeTable> VisitTypeTables { get; set; }
        public virtual DbSet<ModelTable> ModelTables { get; set; }
        public virtual DbSet<UnitStatusMasterTable> UnitStatusMasterTables { get; set; }
        public virtual DbSet<vw_CheckFacility> vw_CheckFacility { get; set; }
        public virtual DbSet<vw_CheckRoomlist> vw_CheckRoomlist { get; set; }
        public virtual DbSet<vw_CRM_LeadData> vw_CRM_LeadData { get; set; }
        public virtual DbSet<vw_Project> vw_Project { get; set; }
        public virtual DbSet<vw_Resale> vw_Resale { get; set; }
        public virtual DbSet<vw_rpt_Deposit> vw_rpt_Deposit { get; set; }
        public virtual DbSet<vw_rpt_Rent> vw_rpt_Rent { get; set; }
        public virtual DbSet<vw_rpt_Resale> vw_rpt_Resale { get; set; }
        public virtual DbSet<vw_rpt_Reservations> vw_rpt_Reservations { get; set; }
        public virtual DbSet<vw_rptCheckroom> vw_rptCheckroom { get; set; }
        public virtual DbSet<RoleAdminMenu> RoleAdminMenus { get; set; }
        public virtual DbSet<DepositAttachment> DepositAttachments { get; set; }
        public virtual DbSet<RentAttachment> RentAttachments { get; set; }
        public virtual DbSet<ReservationsAttachment> ReservationsAttachments { get; set; }
        public virtual DbSet<DraftDocumentAttachment> DraftDocumentAttachments { get; set; }
        public virtual DbSet<AttachmentStatusType> AttachmentStatusTypes { get; set; }
        public virtual DbSet<DepositAttachmentHistory> DepositAttachmentHistories { get; set; }
        public virtual DbSet<vw_DepositAttachmentHistory> vw_DepositAttachmentHistory { get; set; }
        public virtual DbSet<DraftDocumentAttachmentHistory> DraftDocumentAttachmentHistories { get; set; }
        public virtual DbSet<RentAttachmentHistory> RentAttachmentHistories { get; set; }
        public virtual DbSet<ReservationsAttachmentHistory> ReservationsAttachmentHistories { get; set; }
        public virtual DbSet<vw_DraftDocumentAttachmentHistory> vw_DraftDocumentAttachmentHistory { get; set; }
        public virtual DbSet<vw_RentAttachmentHistory> vw_RentAttachmentHistory { get; set; }
        public virtual DbSet<vw_ReservationsAttachmentHistory> vw_ReservationsAttachmentHistory { get; set; }
        public virtual DbSet<MasCountry> MasCountries { get; set; }
        public virtual DbSet<MasMedia> MasMedias { get; set; }
        public virtual DbSet<MasAge> MasAges { get; set; }
        public virtual DbSet<MasBudget> MasBudgets { get; set; }
        public virtual DbSet<MasOccupation> MasOccupations { get; set; }
        public virtual DbSet<MasPurpose> MasPurposes { get; set; }
        public virtual DbSet<MasSalary> MasSalaries { get; set; }
        public virtual DbSet<MasMaritalStatu> MasMaritalStatus { get; set; }
        public virtual DbSet<MasReason> MasReasons { get; set; }
        public virtual DbSet<CallVisitMedia> CallVisitMedias { get; set; }
        public virtual DbSet<CallVisitPurpose> CallVisitPurposes { get; set; }
        public virtual DbSet<CallVisitReason> CallVisitReasons { get; set; }
        public virtual DbSet<CallVisitCompareProject> CallVisitCompareProjects { get; set; }
        public virtual DbSet<MasAcitivity> MasAcitivities { get; set; }
        public virtual DbSet<MasTopic> MasTopics { get; set; }
        public virtual DbSet<CallVisitActivity> CallVisitActivities { get; set; }
        public virtual DbSet<vw_CallVisitActivity> vw_CallVisitActivity { get; set; }
        public virtual DbSet<MasPDPA> MasPDPAs { get; set; }
        public virtual DbSet<CallVisitPDPA> CallVisitPDPAs { get; set; }
        public virtual DbSet<PDPALog> PDPALogs { get; set; }
        public virtual DbSet<vw_MainCallVisit> vw_MainCallVisit { get; set; }
        public virtual DbSet<MasSale> MasSales { get; set; }
        public virtual DbSet<vw_UnitsDetails> vw_UnitsDetails { get; set; }
        public virtual DbSet<vw_LeadCallVisit> vw_LeadCallVisit { get; set; }
        public virtual DbSet<CallVisit> CallVisits { get; set; }
        public virtual DbSet<vw_Rental> vw_Rental { get; set; }
        public virtual DbSet<vw_Reservations> vw_Reservations { get; set; }
        public virtual DbSet<CRM_Contacts> CRM_Contacts { get; set; }
        public virtual DbSet<vw_CRM_Contract> vw_CRM_Contract { get; set; }
        public virtual DbSet<ReservationsShop> ReservationsShops { get; set; }
        public virtual DbSet<ReservationsTable> ReservationsTables { get; set; }
        public virtual DbSet<RentTable> RentTables { get; set; }
        public virtual DbSet<MasZipCode> MasZipCodes { get; set; }
        public virtual DbSet<ContactReasonCancel> ContactReasonCancels { get; set; }
        public virtual DbSet<MasReasonCancelForm> MasReasonCancelForms { get; set; }
        public virtual DbSet<ProjectTable> ProjectTables { get; set; }
    
        public virtual ObjectResult<sp_MainCallVisit_Result> sp_MainCallVisit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MainCallVisit_Result>("sp_MainCallVisit");
        }
    }
}
