//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCodeTable
    {
        public int DocumentCodeID { get; set; }
        public string DocumentCode { get; set; }
        public string DocumentCodeDesc { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
