//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasZipCode
    {
        public int ZipCodeID { get; set; }
        public Nullable<double> TambonID { get; set; }
        public string TambonThai { get; set; }
        public string TambonEng { get; set; }
        public string TambonThaiShort { get; set; }
        public string TambonEngShort { get; set; }
        public string DistrictID { get; set; }
        public string DistrictThai { get; set; }
        public string DistrictEng { get; set; }
        public string DistrictThaiShort { get; set; }
        public string DistrictEngShort { get; set; }
        public Nullable<double> ProvinceID { get; set; }
        public string ProvinceThai { get; set; }
        public string ProvinceEng { get; set; }
        public string Region { get; set; }
        public string Regions { get; set; }
        public string RegionTH { get; set; }
        public string BangkokMetropolitanRegion { get; set; }
        public string PostalCodeRemark { get; set; }
        public string PostCodeMain { get; set; }
        public string PostCodeAll { get; set; }
    }
}
