//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDPALog
    {
        public int PDPALogID { get; set; }
        public int CallVisitID { get; set; }
        public Nullable<int> PDPAID { get; set; }
        public string Activity { get; set; }
        public string PDPATitle { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
    }
}
