//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetailTable
    {
        public long ProjectDetailID { get; set; }
        public Nullable<decimal> MaintenanceCharge { get; set; }
        public Nullable<decimal> WaterCharge { get; set; }
        public string ProjectDetaiOther { get; set; }
        public string ProjectDetaiDescription { get; set; }
        public Nullable<long> Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<long> Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> ProjectID { get; set; }
    }
}
