//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentTable
    {
        public long RentID { get; set; }
        public string RentNo { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public string RentAt { get; set; }
        public Nullable<long> RentStatus { get; set; }
        public Nullable<long> RTContractID { get; set; }
        public Nullable<int> RentPeriod { get; set; }
        public Nullable<System.DateTime> RentStartDate { get; set; }
        public Nullable<System.DateTime> RentEndDate { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public string DayofDue { get; set; }
        public Nullable<int> RoomInsuranceQty { get; set; }
        public Nullable<decimal> RoomInsuranceAmt { get; set; }
        public Nullable<int> RoomDepositQty { get; set; }
        public Nullable<decimal> RoomDepositAmt { get; set; }
        public Nullable<decimal> MulctPrice { get; set; }
        public string CheckRoomRemarkRent { get; set; }
        public string RentRemark { get; set; }
        public Nullable<bool> IsEnd { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string DocRef { get; set; }
        public Nullable<long> Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<long> Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> DepositID { get; set; }
        public Nullable<long> ReservationsID { get; set; }
        public Nullable<decimal> RoomFurnitureAmt { get; set; }
        public string RentFurnitureNo { get; set; }
        public Nullable<int> RoomFurnitureQty { get; set; }
        public Nullable<int> RoomFurnitureDepositQty { get; set; }
        public Nullable<decimal> RoomFurnitureDepositAmt { get; set; }
        public Nullable<decimal> CommissionPrice { get; set; }
        public Nullable<bool> CommissionChecked { get; set; }
        public Nullable<decimal> Pay_Cash { get; set; }
        public Nullable<decimal> Pay_Cashier { get; set; }
        public string Pay_CashierBank { get; set; }
        public string Pay_CashierNo { get; set; }
        public Nullable<System.DateTime> Pay_CashierDate { get; set; }
        public Nullable<decimal> Pay_TransferCash { get; set; }
        public string Pay_TransferBankNo { get; set; }
        public string Pay_TransferBankName { get; set; }
        public Nullable<System.DateTime> Pay_TransferCashDate { get; set; }
        public Nullable<decimal> Com_Pay_Cash { get; set; }
        public Nullable<decimal> Com_Pay_Cashier { get; set; }
        public string Com_Pay_CashierBank { get; set; }
        public string Com_Pay_CashierNo { get; set; }
        public Nullable<System.DateTime> Com_Pay_CashierDate { get; set; }
        public Nullable<decimal> Com_Pay_TransferCash { get; set; }
        public string Com_Pay_TransferBankNo { get; set; }
        public string Com_Pay_TransferBankName { get; set; }
        public Nullable<System.DateTime> Com_Pay_TransferCashDate { get; set; }
        public Nullable<long> CopyRentID { get; set; }
        public string Remark_Cancel { get; set; }
    }
}
