//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentTypeMasterTable
    {
        public int ID { get; set; }
        public Nullable<int> RentTypeID { get; set; }
        public string RentTypeNameTH { get; set; }
        public string RentTypeNameEN { get; set; }
        public Nullable<int> LabelID { get; set; }
    }
}
