//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResaleTable
    {
        public long ResaleID { get; set; }
        public string ResaleNo { get; set; }
        public Nullable<System.DateTime> ResaleDate { get; set; }
        public string ResaleAt { get; set; }
        public Nullable<long> ResaleStatus { get; set; }
        public Nullable<long> RSContractID { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> ContractDiscount { get; set; }
        public Nullable<decimal> TransferDiscount { get; set; }
        public Nullable<decimal> SaleAmt { get; set; }
        public Nullable<decimal> SalePerSqm { get; set; }
        public Nullable<decimal> PriceBFVat { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public string DocRef { get; set; }
        public Nullable<long> Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<long> Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> DepositID { get; set; }
        public Nullable<long> ReservationsID { get; set; }
        public Nullable<decimal> Pay_Cash { get; set; }
        public Nullable<decimal> Pay_Cashier { get; set; }
        public string Pay_CashierBank { get; set; }
        public string Pay_CashierNo { get; set; }
        public Nullable<System.DateTime> Pay_CashierDate { get; set; }
        public Nullable<decimal> Pay_TransferCash { get; set; }
        public string Pay_TransferBankNo { get; set; }
        public string Pay_TransferBankName { get; set; }
        public Nullable<System.DateTime> Pay_TransferCashDate { get; set; }
        public Nullable<decimal> TransferFeeAmt { get; set; }
        public Nullable<decimal> ContactAmt { get; set; }
    }
}
