//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationsShop
    {
        public int ReservationsShopID { get; set; }
        public int ReservationsID { get; set; }
        public string ShopName { get; set; }
        public string ShopAim { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
