//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationsTable
    {
        public int ReservationsID { get; set; }
        public string ReservationsNo { get; set; }
        public Nullable<System.DateTime> ReservationsDate { get; set; }
        public string ReservationsAt { get; set; }
        public string DocRef { get; set; }
        public string ReservationsType { get; set; }
        public Nullable<long> ReservationsStatus { get; set; }
        public Nullable<long> RVCustomerID { get; set; }
        public Nullable<System.DateTime> DueDateSignContact { get; set; }
        public Nullable<long> DSContactID { get; set; }
        public Nullable<int> RentPeriod { get; set; }
        public Nullable<System.DateTime> RentStartDate { get; set; }
        public Nullable<System.DateTime> RentEndDate { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public string DayofDue { get; set; }
        public Nullable<decimal> RoomInsuranceAmt { get; set; }
        public Nullable<int> RoomInsuranceQty { get; set; }
        public Nullable<decimal> RoomDepositAmt { get; set; }
        public Nullable<int> RoomDepositQty { get; set; }
        public Nullable<decimal> ReservationsAmt { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<decimal> SaleAmt { get; set; }
        public Nullable<decimal> SalePerSqm { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<decimal> ContactAmount { get; set; }
        public Nullable<decimal> Pay_Cash { get; set; }
        public Nullable<decimal> Pay_Cashier { get; set; }
        public string Pay_CashierBank { get; set; }
        public string Pay_CashierNo { get; set; }
        public Nullable<System.DateTime> Pay_CashierDate { get; set; }
        public Nullable<decimal> Pay_TransferCash { get; set; }
        public string Pay_TransferBankNo { get; set; }
        public string Pay_TransferBankName { get; set; }
        public Nullable<System.DateTime> Pay_TransferCashDate { get; set; }
        public string Remark { get; set; }
        public string Remark_Cancel { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<long> DepositID { get; set; }
        public Nullable<bool> IsContact { get; set; }
    }
}
