//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CRM_Contract
    {
        public string NameShortPre { get; set; }
        public string NameFullPre { get; set; }
        public string CustomerTypeNameThai { get; set; }
        public string CitizenID { get; set; }
        public string PassportID { get; set; }
        public string Address { get; set; }
        public string Tel1 { get; set; }
        public string FaxNo { get; set; }
        public Nullable<int> CountUnits { get; set; }
        public long ContactsID { get; set; }
        public string AddressNo { get; set; }
        public string Moo { get; set; }
        public string Soi { get; set; }
        public string SubDistrict { get; set; }
        public string Road { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string ZipCode { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CitizenIssue { get; set; }
        public Nullable<System.DateTime> CitizenExp { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Age { get; set; }
        public string CitizenProvince { get; set; }
        public string AddressNo_Work { get; set; }
        public Nullable<int> PROVINCE_ID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Tel2 { get; set; }
        public string Expr1 { get; set; }
        public bool UnExpireIDCard { get; set; }
        public bool IsForeign { get; set; }
        public bool IsJuristic { get; set; }
        public string JuristicPerson { get; set; }
    }
}
