//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_LeadCallVisit
    {
        public int CallVisitID { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string LineID { get; set; }
        public string Address { get; set; }
        public string Building { get; set; }
        public string Moo { get; set; }
        public string Floor { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public Nullable<int> SubDistrictID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string PROVINCE_NAME { get; set; }
        public string AMPHUR_NAME { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string FullAddress { get; set; }
        public string IDCard { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public string SaleName { get; set; }
    }
}
