//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rptCheckroom
    {
        public long CheckRoomID { get; set; }
        public string CheckRoomDesc { get; set; }
        public Nullable<bool> IsQty { get; set; }
        public Nullable<long> CheckType { get; set; }
        public string DocsType { get; set; }
        public string CheckRoomQty { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
