//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rpt_Resale
    {
        public long DepositID { get; set; }
        public Nullable<long> DSContactID { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public Nullable<long> DSTypeID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsRent { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<decimal> RentPriceStart { get; set; }
        public Nullable<decimal> RentPriceEnd { get; set; }
        public Nullable<decimal> SalePriceStart { get; set; }
        public Nullable<decimal> SalePriceEnd { get; set; }
        public string FirstName { get; set; }
        public string Tel1 { get; set; }
        public string UnitsCode { get; set; }
        public Nullable<long> UnitID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public string DescriptionTH { get; set; }
        public string Floor { get; set; }
        public Nullable<decimal> RoomArea { get; set; }
        public string RentTypeNameTH { get; set; }
        public string ResaleNo { get; set; }
        public Nullable<System.DateTime> ResaleDate { get; set; }
        public string ResaleAt { get; set; }
        public Nullable<long> ResaleStatus { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> ContractDiscount { get; set; }
        public Nullable<decimal> TransferDiscount { get; set; }
        public Nullable<decimal> SaleAmt { get; set; }
        public Nullable<decimal> SalePerSqm { get; set; }
        public Nullable<decimal> PriceBFVat { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public long ResaleID { get; set; }
        public Nullable<long> RSContractID { get; set; }
        public string UnitCls { get; set; }
        public string RentCls { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<long> InChargeBy { get; set; }
        public string RoomType { get; set; }
        public Nullable<decimal> Pay_Cash { get; set; }
        public Nullable<decimal> Pay_Cashier { get; set; }
        public string Pay_CashierBank { get; set; }
        public string Pay_CashierNo { get; set; }
        public Nullable<System.DateTime> Pay_CashierDate { get; set; }
        public Nullable<decimal> Pay_TransferCash { get; set; }
        public string Pay_TransferBankNo { get; set; }
        public string Pay_TransferBankName { get; set; }
        public Nullable<System.DateTime> Pay_TransferCashDate { get; set; }
        public string ResaleDate_TH_DDMMYYYY { get; set; }
        public string TransferDate_TH_DDMMYYYY { get; set; }
        public string Pay_CashierDate_TH_DDMMYYYY { get; set; }
        public string Pay_TransferCashDate_TH_DDMMYYYY { get; set; }
        public string SalePrice_TH_Currency { get; set; }
        public string ContractDiscount_TH_Currency { get; set; }
        public string TransferDiscount_TH_Currency { get; set; }
        public string SaleAmt_TH_Currency { get; set; }
        public string SalePerSqm_TH_Currency { get; set; }
        public string PriceBFVat_TH_Currency { get; set; }
        public string VatAmt_TH_Currency { get; set; }
        public string NetPrice_TH_Currency { get; set; }
        public string Pay_Cash_TH_Currency { get; set; }
        public string Pay_Cashier_TH_Currency { get; set; }
        public string Pay_TransferCash_TH_Currency { get; set; }
        public string TransferFeeAmt_TH_Currency { get; set; }
        public Nullable<decimal> TransferFeeAmt { get; set; }
        public int Check_TransferFeeAmt { get; set; }
        public int Check_Pay_Cash { get; set; }
        public int Check_Pay_Cashier { get; set; }
        public int Check_Pay_TransferCash { get; set; }
        public int Check_ContactAmt { get; set; }
        public string DS_FirstName { get; set; }
        public string DS_CitizenID { get; set; }
        public Nullable<System.DateTime> DS_CitizenIssue { get; set; }
        public Nullable<System.DateTime> DS_CitizenExp { get; set; }
        public string DS_Tel1 { get; set; }
        public string DS_AddressNo { get; set; }
        public string DS_Moo { get; set; }
        public string DS_Soi { get; set; }
        public string DS_Road { get; set; }
        public string DS_ZipCode { get; set; }
        public string DS_Nationality { get; set; }
        public Nullable<int> DS_Age { get; set; }
        public string DS_PROVINCE_NAME { get; set; }
        public string DS_AMPHUR_NAME { get; set; }
        public string DS_SubDistrict { get; set; }
        public string DS_IDCard_Province { get; set; }
        public Nullable<bool> DS_UnExpireIDCard { get; set; }
        public string DS_AddressNo_Work { get; set; }
        public string DS_Address { get; set; }
        public string RS_FirstName { get; set; }
        public string RS_CitizenID { get; set; }
        public Nullable<System.DateTime> RS_CitizenIssue { get; set; }
        public Nullable<System.DateTime> RS_CitizenExp { get; set; }
        public string RS_Tel1 { get; set; }
        public string RS_AddressNo { get; set; }
        public string RS_Moo { get; set; }
        public string RS_Soi { get; set; }
        public string RS_Road { get; set; }
        public string RS_ZipCode { get; set; }
        public string RS_Nationality { get; set; }
        public Nullable<int> RS_Age { get; set; }
        public string RS_PROVINCE_NAME { get; set; }
        public string RS_AMPHUR_NAME { get; set; }
        public string RS_SubDistrict { get; set; }
        public string RS_IDCard_Province { get; set; }
        public Nullable<bool> RN_UnExpireIDCard { get; set; }
        public string RN_AddressNo_Work { get; set; }
        public string RS_Address { get; set; }
        public string RoomUnitType { get; set; }
        public string ReviserName { get; set; }
        public string CreatorName { get; set; }
        public Nullable<decimal> ContactAmt { get; set; }
        public string ContactAmt_TH_Currency { get; set; }
        public string RoomNo { get; set; }
        public Nullable<decimal> RV_RemainingAmount { get; set; }
        public Nullable<decimal> RV_ContactAmount { get; set; }
        public string RV_RemainingAmount_TH_Currency { get; set; }
        public string RV_ContactAmount_TH_Currency { get; set; }
        public string RS_Address_Full { get; set; }
        public string DS_Address_Full { get; set; }
        public Nullable<long> DevelopmentID { get; set; }
        public string DevelopmentName { get; set; }
        public string DS_Tel1_Show { get; set; }
        public string RS_Tel1_Show { get; set; }
        public string Building { get; set; }
    }
}
