//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Reservations
    {
        public long DepositID { get; set; }
        public Nullable<long> DSContactID { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public Nullable<long> DSTypeID { get; set; }
        public Nullable<bool> IsRent { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<decimal> RentPriceStart { get; set; }
        public Nullable<decimal> RentPriceEnd { get; set; }
        public Nullable<decimal> SalePriceStart { get; set; }
        public Nullable<decimal> SalePriceEnd { get; set; }
        public string FirstName { get; set; }
        public string Tel1 { get; set; }
        public string UnitsCode { get; set; }
        public Nullable<long> UnitID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<int> UnitSatatusID { get; set; }
        public string DescriptionTH { get; set; }
        public string Floor { get; set; }
        public Nullable<decimal> RoomArea { get; set; }
        public string RentTypeNameTH { get; set; }
        public string UnitCls { get; set; }
        public string RentCls { get; set; }
        public Nullable<System.DateTime> RentStartDate { get; set; }
        public Nullable<System.DateTime> RentEndDate { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> ReservationsDate { get; set; }
        public Nullable<long> Reviser { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public int ReservationsID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> RentPeriod { get; set; }
        public string DayofDue { get; set; }
        public string ReservationsNo { get; set; }
        public Nullable<long> InChargeBy { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public string RoomType { get; set; }
        public Nullable<long> RVCustomerID { get; set; }
        public string Remark_Cancel { get; set; }
        public int ISContact { get; set; }
        public string ReservationsType { get; set; }
    }
}
