//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rpt_Reservations
    {
        public Nullable<decimal> MaintenanceCharge { get; set; }
        public Nullable<decimal> WaterCharge { get; set; }
        public Nullable<long> CountKey { get; set; }
        public Nullable<bool> KeyIsAgent { get; set; }
        public Nullable<bool> KeyIsJuristic { get; set; }
        public string ProjectAddress { get; set; }
        public string CheckRoomRemarkDeposit { get; set; }
        public string FacilityOther { get; set; }
        public string FacilityRemark { get; set; }
        public string UnitsCode { get; set; }
        public string UnitsName { get; set; }
        public string Floor { get; set; }
        public string RoomNo { get; set; }
        public Nullable<decimal> RoomArea { get; set; }
        public Nullable<int> BedRoomQty { get; set; }
        public Nullable<int> LivingRoomQty { get; set; }
        public Nullable<int> ToiletRoomQty { get; set; }
        public Nullable<int> KitchenRoomQty { get; set; }
        public string ProjectName { get; set; }
        public string DevelopmentName { get; set; }
        public string DS_FirstName { get; set; }
        public string DS_CitizenID { get; set; }
        public Nullable<System.DateTime> DS_CitizenIssue { get; set; }
        public Nullable<System.DateTime> DS_CitizenExp { get; set; }
        public string DS_Tel1 { get; set; }
        public string DS_AddressNo { get; set; }
        public string DS_ZipCode { get; set; }
        public string DS_Nationality { get; set; }
        public Nullable<int> DS_Age { get; set; }
        public string DS_PROVINCE_NAME { get; set; }
        public string DS_AMPHUR_NAME { get; set; }
        public string DS_SubDistrict { get; set; }
        public string RV_FirstName { get; set; }
        public string RV_CitizenID { get; set; }
        public Nullable<System.DateTime> RV_CitizenIssue { get; set; }
        public Nullable<System.DateTime> RV_CitizenExp { get; set; }
        public string RV_Tel1 { get; set; }
        public string RV_AddressNo { get; set; }
        public string RV_ZipCode { get; set; }
        public string RV_Nationality { get; set; }
        public Nullable<int> RV_Age { get; set; }
        public string RV_PROVINCE_NAME { get; set; }
        public string RV_AMPHUR_NAME { get; set; }
        public string RV_SubDistrict { get; set; }
        public string BankName { get; set; }
        public string BankTypeNameTH { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string DS_IDCard_Province { get; set; }
        public string RV_IDCard_Province { get; set; }
        public string RoomType { get; set; }
        public string RV_Moo { get; set; }
        public string RV_Soi { get; set; }
        public string RV_Road { get; set; }
        public string DS_Moo { get; set; }
        public string DS_Soi { get; set; }
        public string DS_Road { get; set; }
        public bool DS_UnExpireIDCard { get; set; }
        public bool RV_UnExpireIDCard { get; set; }
        public string RV_AddressNo_Work { get; set; }
        public string DS_AddressNo_Work { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public string RentPrice_ThaiCurrentcy { get; set; }
        public Nullable<decimal> RoomInsuranceAmt { get; set; }
        public string RoomInsuranceAmt_ThaiCurrentcy { get; set; }
        public Nullable<decimal> RoomDepositAmt { get; set; }
        public string RoomDepositAmt_ThaiCurrentcy { get; set; }
        public Nullable<decimal> SaleAmt { get; set; }
        public string SaleAmt_ThaiCurrentcy { get; set; }
        public Nullable<decimal> SalePerSqm { get; set; }
        public string SalePerSqm_ThaiCurrentcy { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public string CashAmount_ThaiCurrentcy { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public string RemainingAmount_ThaiCurrentcy { get; set; }
        public Nullable<decimal> Pay_Cash { get; set; }
        public string Pay_Cash_ThaiCurrentcy { get; set; }
        public Nullable<decimal> Pay_Cashier { get; set; }
        public string Pay_Cashier_ThaiCurrentcy { get; set; }
        public Nullable<decimal> Pay_TransferCash { get; set; }
        public string Pay_TransferCash_ThaiCurrentcy { get; set; }
        public int ReservationsID { get; set; }
        public string ReservationsNo { get; set; }
        public Nullable<System.DateTime> ReservationsDate { get; set; }
        public string ReservationsAt { get; set; }
        public string DocRef { get; set; }
        public string ReservationsType { get; set; }
        public Nullable<long> ReservationsStatus { get; set; }
        public Nullable<System.DateTime> DueDateSignContact { get; set; }
        public string Remark { get; set; }
        public string Remark_Cancel { get; set; }
        public string Expr1 { get; set; }
        public string DayofDue { get; set; }
        public Nullable<int> RentPeriod { get; set; }
        public Nullable<System.DateTime> RentStartDate { get; set; }
        public Nullable<System.DateTime> RentEndDate { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string Pay_CashierBank { get; set; }
        public string Pay_CashierNo { get; set; }
        public Nullable<System.DateTime> Pay_CashierDate { get; set; }
        public string Pay_TransferBankNo { get; set; }
        public Nullable<System.DateTime> Pay_TransferCashDate { get; set; }
        public string RentStartDate_TH { get; set; }
        public string RentEndDateDate_TH { get; set; }
        public string PeriodStratEndRent_TH { get; set; }
        public string TransferDate_TH { get; set; }
        public string Pay_CashierDate_TH { get; set; }
        public string Pay_TransferCashDate_TH { get; set; }
        public string DueDateSignContact_TH { get; set; }
        public string ReservationsDate_TH { get; set; }
        public Nullable<decimal> SumPayAmt { get; set; }
        public string SumPayAmt_TH { get; set; }
        public string Expr3 { get; set; }
        public string CreatorName { get; set; }
        public string ReviserName { get; set; }
        public int CHECKED_Pay_Cash { get; set; }
        public int CHECKED_Pay_Cashier { get; set; }
        public int CHECKED_TransferCash { get; set; }
        public string Pay_CashierBankName { get; set; }
        public string ReservationsAmt_TH { get; set; }
        public Nullable<decimal> ReservationsAmt { get; set; }
        public string Pay_TransferBankName { get; set; }
        public Nullable<decimal> ContactAmount { get; set; }
        public string ContactAmount_THCurrentcy { get; set; }
        public string TempRep_Unit { get; set; }
        public string TempRep_RoomNo { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public string DepositNo { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> DevelopmentID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public bool IsCancel { get; set; }
        public string DS_Tel1_Show { get; set; }
        public string RV_Tel1_Show { get; set; }
    }
}
