//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rpt_Rent
    {
        public string RentNo { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public string RentAt { get; set; }
        public Nullable<int> RentPeriod { get; set; }
        public Nullable<System.DateTime> RentStartDate { get; set; }
        public Nullable<System.DateTime> RentEndDate { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public string DayofDue { get; set; }
        public Nullable<int> RoomInsuranceQty { get; set; }
        public Nullable<decimal> RoomInsuranceAmt { get; set; }
        public Nullable<int> RoomDepositQty { get; set; }
        public Nullable<decimal> RoomDepositAmt { get; set; }
        public string CheckRoomRemarkRent { get; set; }
        public string RentRemark { get; set; }
        public Nullable<decimal> MaintenanceCharge { get; set; }
        public Nullable<decimal> WaterCharge { get; set; }
        public Nullable<long> CountKey { get; set; }
        public Nullable<bool> KeyIsAgent { get; set; }
        public Nullable<bool> KeyIsJuristic { get; set; }
        public string ProjectAddress { get; set; }
        public string CheckRoomRemarkDeposit { get; set; }
        public string FacilityOther { get; set; }
        public string FacilityRemark { get; set; }
        public string UnitsCode { get; set; }
        public string UnitsName { get; set; }
        public string Floor { get; set; }
        public string RoomNo { get; set; }
        public Nullable<decimal> RoomArea { get; set; }
        public Nullable<int> BedRoomQty { get; set; }
        public Nullable<int> LivingRoomQty { get; set; }
        public Nullable<int> ToiletRoomQty { get; set; }
        public Nullable<int> KitchenRoomQty { get; set; }
        public string ProjectName { get; set; }
        public string DevelopmentName { get; set; }
        public long RentID { get; set; }
        public string DS_FirstName { get; set; }
        public string DS_CitizenID { get; set; }
        public Nullable<System.DateTime> DS_CitizenIssue { get; set; }
        public Nullable<System.DateTime> DS_CitizenExp { get; set; }
        public string DS_Tel1 { get; set; }
        public string DS_AddressNo { get; set; }
        public string DS_ZipCode { get; set; }
        public string DS_Nationality { get; set; }
        public Nullable<int> DS_Age { get; set; }
        public string DS_PROVINCE_NAME { get; set; }
        public string DS_AMPHUR_NAME { get; set; }
        public string DS_SubDistrict { get; set; }
        public string RN_FirstName { get; set; }
        public string RN_CitizenID { get; set; }
        public Nullable<System.DateTime> RN_CitizenIssue { get; set; }
        public Nullable<System.DateTime> RN_CitizenExp { get; set; }
        public string RN_Tel1 { get; set; }
        public string RN_AddressNo { get; set; }
        public string RN_ZipCode { get; set; }
        public string RN_Nationality { get; set; }
        public Nullable<int> RN_Age { get; set; }
        public string RN_PROVINCE_NAME { get; set; }
        public string RN_AMPHUR_NAME { get; set; }
        public string RN_SubDistrict { get; set; }
        public string BankName { get; set; }
        public string BankTypeNameTH { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public string DS_IDCard_Province { get; set; }
        public string RN_IDCard_Province { get; set; }
        public string RoomType { get; set; }
        public string RN_Moo { get; set; }
        public string RN_Soi { get; set; }
        public string RN_Road { get; set; }
        public string DS_Moo { get; set; }
        public string DS_Soi { get; set; }
        public string DS_Road { get; set; }
        public Nullable<decimal> MulctPrice { get; set; }
        public bool DS_UnExpireIDCard { get; set; }
        public bool RN_UnExpireIDCard { get; set; }
        public string RN_AddressNo_Work { get; set; }
        public string DS_AddressNo_Work { get; set; }
        public decimal RoomFurnitureAmt { get; set; }
        public string RentFurnitureNo { get; set; }
        public string ThaiCurrentcyRoomFurnitureAmt { get; set; }
        public Nullable<decimal> CommissionPrice { get; set; }
        public Nullable<int> IsCommissionChecked { get; set; }
        public string PeriodStratEndRent_TH { get; set; }
        public string CreatorName { get; set; }
        public string ReviserName { get; set; }
        public Nullable<int> RoomFurnitureQty { get; set; }
        public Nullable<int> RoomFurnitureDepositQty { get; set; }
        public Nullable<decimal> RoomFurnitureDepositAmt { get; set; }
        public Nullable<decimal> Pay_Cash { get; set; }
        public Nullable<decimal> Pay_Cashier { get; set; }
        public string Pay_CashierBank { get; set; }
        public string Pay_CashierNo { get; set; }
        public Nullable<System.DateTime> Pay_CashierDate { get; set; }
        public Nullable<decimal> Pay_TransferCash { get; set; }
        public string Pay_TransferBankNo { get; set; }
        public string Pay_TransferBankName { get; set; }
        public Nullable<System.DateTime> Pay_TransferCashDate { get; set; }
        public decimal Sum_RoomInsuranceAmt { get; set; }
        public decimal Sum_RoomDepositAmt { get; set; }
        public decimal Sum_RoomFurnitureAmt { get; set; }
        public decimal Sum_RoomFurnitureDepositAmt { get; set; }
        public int CHECKED_Pay_Cash { get; set; }
        public int CHECKED_Pay_Cashier { get; set; }
        public int CHECKED_TransferCash { get; set; }
        public int CHECKED_RoomInsuranceAmt { get; set; }
        public int CHECKED_RoomDepositAmt { get; set; }
        public int CHECKED_RoomFurnitureAmt_INS { get; set; }
        public int CHECKED_RoomFurnitureDepositAmt { get; set; }
        public string Pay_CashierDate_TH { get; set; }
        public string Pay_TransferCashDate_TH { get; set; }
        public string RentDate_TH { get; set; }
        public string Pay_CashierBankName { get; set; }
        public Nullable<int> ReservationsAmt { get; set; }
        public string TempRep_RoomNo { get; set; }
        public string Building { get; set; }
        public bool CommissionChecked { get; set; }
        public Nullable<decimal> Com_Pay_Cash { get; set; }
        public Nullable<decimal> Com_Pay_Cashier { get; set; }
        public string Com_Pay_CashierBank { get; set; }
        public string Com_Pay_CashierNo { get; set; }
        public Nullable<System.DateTime> Com_Pay_CashierDate { get; set; }
        public Nullable<decimal> Com_Pay_TransferCash { get; set; }
        public string Com_Pay_TransferBankNo { get; set; }
        public string Com_Pay_TransferBankName { get; set; }
        public Nullable<System.DateTime> Com_Pay_TransferCashDate { get; set; }
        public int CHECKED_Com_Pay_Cash { get; set; }
        public int CHECKED_Com_Pay_Cashier { get; set; }
        public int CHECKED_Com_Pay_TransferCash { get; set; }
        public string DateTH_Com_Pay_CashierDate { get; set; }
        public string DateTH_Com_Pay_TransferCashDate { get; set; }
        public long ProjectID { get; set; }
        public long DevelopmentID { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string DS_Tel1_Show { get; set; }
        public string RN_Tel1_Show { get; set; }
        public Nullable<long> ReservationsID { get; set; }
        public Nullable<long> CopyRentID { get; set; }
        public Nullable<bool> IsJuristic { get; set; }
        public string JuristicPerson { get; set; }
        public string RentStartDate_TH { get; set; }
        public string RentEndDate_TH { get; set; }
        public string ShopName { get; set; }
        public string ShopAim { get; set; }
        public Nullable<decimal> SumAmt { get; set; }
        public string SumAmt_ThaiCurrentcy { get; set; }
    }
}
