//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_rpt_Deposit
    {
        public string DepositNo { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> DepositStart { get; set; }
        public Nullable<System.DateTime> DepositEnd { get; set; }
        public Nullable<long> CountKey { get; set; }
        public Nullable<bool> KeyIsAgent { get; set; }
        public Nullable<bool> KeyIsJuristic { get; set; }
        public string BankID { get; set; }
        public Nullable<long> BankTypeID { get; set; }
        public string BankNo { get; set; }
        public string BankName { get; set; }
        public string BankTypeNameTH { get; set; }
        public string BankNameFull { get; set; }
        public string CitizenID { get; set; }
        public Nullable<System.DateTime> CitizenIssue { get; set; }
        public Nullable<System.DateTime> CitizenExp { get; set; }
        public string CitizenProvince { get; set; }
        public string Tel1 { get; set; }
        public string AddressNo { get; set; }
        public string Moo { get; set; }
        public string Soi { get; set; }
        public string Village { get; set; }
        public string Road { get; set; }
        public string ZipCode { get; set; }
        public string AddressNo_Work { get; set; }
        public string UnitsCode { get; set; }
        public Nullable<decimal> RoomArea { get; set; }
        public string RoomNo { get; set; }
        public string Floor { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<int> SalePriceStart { get; set; }
        public Nullable<int> SalePriceEnd { get; set; }
        public Nullable<bool> IsRent { get; set; }
        public Nullable<int> RentPriceStart { get; set; }
        public Nullable<int> RentPriceEnd { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string DevelopmentCode { get; set; }
        public string DevelopmentName { get; set; }
        public long DepositID { get; set; }
        public string CheckRoomRemarkDeposit { get; set; }
        public string RoomType { get; set; }
        public string Tel2 { get; set; }
        public string Email { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string SubDistrict { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public Nullable<long> DeveloperID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public Nullable<long> InChargeBy { get; set; }
        public string InChargeByName { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public string ReasonCancel { get; set; }
        public string DescriptionTH { get; set; }
        public string DescriptionENG { get; set; }
        public string DS_AddressNo { get; set; }
        public decimal RateComCopyContact { get; set; }
        public string BankNameENGFull { get; set; }
    }
}
