//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ReservationsAttachmentHistory
    {
        public int ReservationsAttachmentHistoryID { get; set; }
        public Nullable<int> ReservationsAttachmentID { get; set; }
        public Nullable<int> AttachmentStatusTypeID { get; set; }
        public string em_name_t_create { get; set; }
        public string em_surname_t_create { get; set; }
        public Nullable<System.DateTime> RevisedDateTime { get; set; }
        public Nullable<long> ReservationsID { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> RevisedDateTime_create { get; set; }
        public string StatusDescription { get; set; }
        public string em_code { get; set; }
        public string em_name_t { get; set; }
        public string em_surname_t { get; set; }
    }
}
