//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Resale
    {
        public long DepositID { get; set; }
        public Nullable<long> DSContactID { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public Nullable<long> DSTypeID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsRent { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<decimal> RentPriceStart { get; set; }
        public Nullable<decimal> RentPriceEnd { get; set; }
        public Nullable<decimal> SalePriceStart { get; set; }
        public Nullable<decimal> SalePriceEnd { get; set; }
        public string FirstName { get; set; }
        public string Tel1 { get; set; }
        public string UnitsCode { get; set; }
        public Nullable<long> UnitID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public string DescriptionTH { get; set; }
        public string Floor { get; set; }
        public Nullable<decimal> RoomArea { get; set; }
        public string RentTypeNameTH { get; set; }
        public string ResaleNo { get; set; }
        public Nullable<System.DateTime> ResaleDate { get; set; }
        public string ResaleAt { get; set; }
        public Nullable<long> ResaleStatus { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> ContractDiscount { get; set; }
        public Nullable<decimal> TransferDiscount { get; set; }
        public Nullable<decimal> SaleAmt { get; set; }
        public Nullable<decimal> SalePerSqm { get; set; }
        public Nullable<decimal> PriceBFVat { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public long ResaleID { get; set; }
        public Nullable<long> RSContractID { get; set; }
        public string slFirstName { get; set; }
        public string slTel { get; set; }
        public string UnitCls { get; set; }
        public string RentCls { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<long> InChargeBy { get; set; }
        public string RoomType { get; set; }
        public string ReservationsNo { get; set; }
        public string ReservationsType { get; set; }
        public Nullable<System.DateTime> ReservationsDate { get; set; }
        public Nullable<decimal> ReservationsAmt { get; set; }
    }
}
