//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.DMPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UnitsDetails
    {
        public Nullable<long> ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public Nullable<long> UnitsID { get; set; }
        public string UnitsCode { get; set; }
        public string UnitsName { get; set; }
        public Nullable<bool> UnitsStatus { get; set; }
        public string Floor { get; set; }
        public string RoomNo { get; set; }
        public Nullable<decimal> RoomArea { get; set; }
        public Nullable<int> BedRoomQty { get; set; }
        public Nullable<int> LivingRoomQty { get; set; }
        public Nullable<int> ToiletRoomQty { get; set; }
        public Nullable<int> KitchenRoomQty { get; set; }
        public string RoomType { get; set; }
        public Nullable<bool> ProjectStatus { get; set; }
        public string DepositNo { get; set; }
        public long DepositID { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public Nullable<long> DSContactID { get; set; }
        public Nullable<long> DSTypeID { get; set; }
        public Nullable<long> DevelopmentID { get; set; }
        public string DevelopmentCode { get; set; }
        public string DevelopmentName { get; set; }
        public Nullable<bool> DevelopmentStatus { get; set; }
        public Nullable<bool> IsRent { get; set; }
        public Nullable<decimal> RentPriceStart { get; set; }
        public Nullable<decimal> RentPriceEnd { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<decimal> SalePriceStart { get; set; }
        public Nullable<decimal> SalePriceEnd { get; set; }
        public string CheckRoomRemarkDeposit { get; set; }
        public string FacilityOther { get; set; }
        public string FacilityRemark { get; set; }
        public Nullable<long> InChargeBy { get; set; }
        public Nullable<System.DateTime> DepositStart { get; set; }
        public Nullable<System.DateTime> DepositEnd { get; set; }
        public Nullable<int> RentTypeID { get; set; }
        public string RentTypeNameTH { get; set; }
        public string RentTypeNameEN { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string DescriptionTH { get; set; }
        public string DescriptionENG { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string NameShortPre { get; set; }
        public string NameFullPre { get; set; }
        public string CustomerTypeNameThai { get; set; }
        public string CitizenID { get; set; }
        public string PassportID { get; set; }
        public string Address { get; set; }
        public string Tel1 { get; set; }
        public string FaxNo { get; set; }
        public Nullable<int> CountUnits { get; set; }
        public Nullable<long> ContactsID { get; set; }
        public string AddressNo { get; set; }
        public string Moo { get; set; }
        public string Soi { get; set; }
        public string SubDistrict { get; set; }
        public string Road { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string ZipCode { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CitizenIssue { get; set; }
        public Nullable<System.DateTime> CitizenExp { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public string Nationality { get; set; }
        public string ProjectDetaiOther { get; set; }
        public string ProjectDetaiDescription { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> MaintenanceCharge { get; set; }
        public Nullable<decimal> WaterCharge { get; set; }
        public Nullable<long> CountKey { get; set; }
        public Nullable<bool> KeyIsAgent { get; set; }
        public Nullable<bool> KeyIsJuristic { get; set; }
        public string ProjectAddress { get; set; }
        public string UnitStatusCls { get; set; }
        public string RentStatusCls { get; set; }
        public string BankID { get; set; }
        public Nullable<long> BankTypeID { get; set; }
        public string BankNo { get; set; }
        public string BankName { get; set; }
        public string DocRef { get; set; }
        public string Building { get; set; }
        public string UnitType { get; set; }
        public Nullable<System.DateTime> ReviseDateTime { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
