//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.EMSG
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentStatusTable
    {
        public int DocumentStatusID { get; set; }
        public string DocumentStatusTH { get; set; }
        public string DocumentStatusEN { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> ClassID { get; set; }
    }
}
