//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.EMSG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMSGEntities : DbContext
    {
        public EMSGEntities()
            : base("name=EMSGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentStatusTable> DocumentStatusTables { get; set; }
        public virtual DbSet<EmpGroupTable> EmpGroupTables { get; set; }
        public virtual DbSet<EmpSpecialTable> EmpSpecialTables { get; set; }
        public virtual DbSet<MessengerTable> MessengerTables { get; set; }
        public virtual DbSet<TimeTable> TimeTables { get; set; }
        public virtual DbSet<WorkTable> WorkTables { get; set; }
        public virtual DbSet<WorkTran> WorkTrans { get; set; }
        public virtual DbSet<WorkTypeTable> WorkTypeTables { get; set; }
        public virtual DbSet<TimeTypeTable> TimeTypeTables { get; set; }
        public virtual DbSet<WorkTable201806> WorkTable201806 { get; set; }
        public virtual DbSet<vw_EmpSpecialGroup> vw_EmpSpecialGroup { get; set; }
        public virtual DbSet<vw_rpt_WorkDocs> vw_rpt_WorkDocs { get; set; }
        public virtual DbSet<vw_SendEmail> vw_SendEmail { get; set; }
        public virtual DbSet<vw_TimeTable> vw_TimeTable { get; set; }
        public virtual DbSet<vw_WorkDocument> vw_WorkDocument { get; set; }
    }
}
