//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.EMSG
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmpSpecialGroup
    {
        public Nullable<long> EmpID { get; set; }
        public string DisplayName { get; set; }
        public int ID { get; set; }
        public Nullable<long> GroupID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
