//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.EMSG
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SendEmail
    {
        public Nullable<int> DocumentStatusID { get; set; }
        public long WorkID { get; set; }
        public long WorkTransID { get; set; }
        public string WorkNO { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public Nullable<long> Creator { get; set; }
        public string Owner_DisplayName { get; set; }
        public string Owner_Email { get; set; }
        public string Creator_DisplayName { get; set; }
        public string Creator_Email { get; set; }
    }
}
