//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.EMSG
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WorkDocument
    {
        public string OwnerDeptCode { get; set; }
        public string DeptCode { get; set; }
        public long WorkID { get; set; }
        public string WorkNO { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerRoad { get; set; }
        public string CustomerDistrict { get; set; }
        public string CustomerPhone { get; set; }
        public string WorkDetail { get; set; }
        public Nullable<long> StartTime { get; set; }
        public Nullable<long> EndTime { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPhone { get; set; }
        public string SpecialOrder { get; set; }
        public string STime { get; set; }
        public string ETime { get; set; }
        public string WorkTypeNameTH { get; set; }
        public string Time_RPT { get; set; }
        public string MessengerNameTH { get; set; }
        public string DocumentStatusTH { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<long> MessengerID { get; set; }
        public Nullable<long> WorkTypeID { get; set; }
        public Nullable<int> STimeID { get; set; }
        public Nullable<int> ETimeID { get; set; }
        public Nullable<int> DocumentStatusID { get; set; }
        public Nullable<long> TimeTypeID { get; set; }
        public string WorkTypeText { get; set; }
        public Nullable<long> Creator { get; set; }
        public string TimeTypeNameTH { get; set; }
        public string OwnerMobile { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public bool UserActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public long SendeMailOpen { get; set; }
        public long SendeMailCance { get; set; }
        public string DeptDescription { get; set; }
        public string ImageURL { get; set; }
        public string CP_TNAME { get; set; }
        public string CP_ENAME { get; set; }
        public string CP_ADDR { get; set; }
        public string CP_BUILD { get; set; }
        public string CP_ROAD { get; set; }
        public string CP_PLACE { get; set; }
        public string CP_FAX { get; set; }
        public string CP_POSTCODE { get; set; }
        public string CP_PHONE { get; set; }
        public string CP_EBUILD { get; set; }
        public long WorkTransID { get; set; }
        public string Expr1 { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ReviserDate { get; set; }
        public Nullable<long> DeptId { get; set; }
        public string WorkTypeTimes { get; set; }
        public int EmpGroupID { get; set; }
        public string GroupEmpOwner { get; set; }
        public string GroupEmpCreate { get; set; }
        public string C_emp_DisplayName { get; set; }
        public string R_emp_DisplayName { get; set; }
        public string C_emp_Company { get; set; }
        public string R_emp_Company { get; set; }
    }
}
