//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.CashAdvance
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvancePayment
    {
        public long AdvancePaymentID { get; set; }
        public string AdvancePaymentNO { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<long> DeptofCost { get; set; }
        public string PaymentOwner { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> DeptId { get; set; }
        public Nullable<long> PositionTransID { get; set; }
        public string ProjectID { get; set; }
        public Nullable<long> BudgetAccountID { get; set; }
        public Nullable<long> BudgetModelID { get; set; }
        public decimal Amount { get; set; }
        public string PaymentRemark { get; set; }
        public Nullable<System.DateTime> ClearCashDate { get; set; }
        public Nullable<long> PaymentTypeID { get; set; }
        public Nullable<System.DateTime> ReceiveCashDate { get; set; }
        public string PVNo { get; set; }
        public Nullable<System.DateTime> ChequeDateIn { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<long> Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> Reviser { get; set; }
        public Nullable<System.DateTime> ReviserDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<long> DeleteBy { get; set; }
        public Nullable<int> DocumentStatusID { get; set; }
        public string DeptofCostCode { get; set; }
        public string DeptCode { get; set; }
    }
}
