//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.CashAdvance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CADEntities : DbContext
    {
        public CADEntities()
            : base("name=CADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvancePayment> AdvancePayments { get; set; }
        public virtual DbSet<Config_Employee> Config_Employee { get; set; }
        public virtual DbSet<ConfigCAD> ConfigCADs { get; set; }
        public virtual DbSet<DocumentStatusTable> DocumentStatusTables { get; set; }
        public virtual DbSet<PaymentTypeTable> PaymentTypeTables { get; set; }
        public virtual DbSet<RefundTable> RefundTables { get; set; }
        public virtual DbSet<RefundTran> RefundTrans { get; set; }
        public virtual DbSet<RefundTypeTable> RefundTypeTables { get; set; }
        public virtual DbSet<vw_AdvancePaymentList> vw_AdvancePaymentList { get; set; }
        public virtual DbSet<vw_ReportAdvancePayment> vw_ReportAdvancePayment { get; set; }
    }
}
