//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.CashAdvance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_Employee
    {
        public long RunningID { get; set; }
        public Nullable<long> ConfigID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
