//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models.CashAdvance
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AdvancePaymentList
    {
        public long AdvancePaymentID { get; set; }
        public string AdvancePaymentNO { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string PaymentOwner { get; set; }
        public string DisplayName { get; set; }
        public string ProjectID { get; set; }
        public decimal AdvancePaymentAmt { get; set; }
        public string PVNo { get; set; }
        public Nullable<System.DateTime> ChequeDateIn { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public string JVNo { get; set; }
        public Nullable<decimal> RefundAmt { get; set; }
        public Nullable<decimal> OtheAmt { get; set; }
        public decimal Balance { get; set; }
        public Nullable<int> DocumentStatusID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> Creator { get; set; }
        public Nullable<System.DateTime> StampDate { get; set; }
    }
}
